kumuluzee:
  name: bikeshare-payments
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/BikesharePaymentsDS
    connection-url: jdbc:postgresql://localhost:5433/bikeshare-payments
    username: postgres
    password: postgres
    max-pool-size: 20