apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikeshare-payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bikeshare-payments
  template:
    metadata:
      labels:
        app: bikeshare-payments
    spec:
      containers:
      - image: nimbostratuz/bikeshare-payments:0.3
        name: bikeshare-payments
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: ibmcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
          value: http://etcd:2379/health
        - name: KUMULUZEE_SERVER_BASEURL
          value: http://159.122.186.200:30422

        # Database
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://postgres:5432/bikeshare-payments
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: pg-user
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: pg-password

        ports:
        - containerPort: 8080
          name: server
          protocol: TCP

        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3


---


apiVersion: v1
kind: Service
metadata:
  name: bikeshare-payments
  labels:
    app: bikeshare-payments
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30422
  selector:
    app: bikeshare-payments